### PR TITLE
[PB-2287]: debug/avatar-upload

### PR DESCRIPTION
**Pull request by jzunigax2**
Some avatar related env values were including trailing /n escape chars.

### CODE REVIEW

**Comment by inxtci** [comment]
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-343-94925eee6b4815811dd3a0496397ddda1488f145

**Comment by jzunigax2** [comment]
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

**Comment by inxtci** [comment]
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-343-4b21a032094ebece13d6107e9780734086767ef7

**Comment by inxtci** [comment]
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-343-e113a0c1e8416b538681bd3d471b7cdc477161c9

**Pull request closed without merging**
